# Generated by Django 5.2.7 on 2025-10-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contentsubmission_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
