# Generated by Django 5.2.7 on 2025-10-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
    ]
