# Generated by Django 5.2.7 on 2025-10-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_login_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referee_package',
            field=models.CharField(blank=True, choices=[('pro', 'Pro Package'), ('silver', 'Silver Package')], max_length=20, null=True),
        ),
    ]
